### PR TITLE
Try move auth

### PR DESCRIPTION
**Pull request by theRealImy**
This is the PR for the move auth from solid-ui to solid-logic.

### CODE REVIEW

**Comment by bourgeoa** [comment]
CI fails on npm publish.

**Comment by theRealImy** [comment]
> CI fails on npm publish.

@bourgeoa > CI fails on npm publish.

@bourgeoa looks like`403 403 Forbidden - PUT https://registry.npmjs.org/folder-pane - You do not have permission to publish "folder-pane". `
However I just manaually trigger CI and it worked... maybe a  hiccup? This should not happen on main anyway.
I can also

**Review by bourgeoa — APPROVED** [review]
We can try to merge to see if it passes npm publish

**Comment by theRealImy** [comment]
> We can try to merge to see if it passes npm publish

@bourgeoa you need to first merge solid-logic and solid-ui otherwise I think it will fail on build anyway...

**Pull request merged**
